ct_map = {
        "256": "Wii Mushroom Gorge",
        "257": "Tour Choco Mountain",
        "258": "DS Luigi's Mansion",
        "259": "Wii Daisy Circuit",
        "260": "SRB2K Green Hill Zone",
        "261": "Goomba Circuit",
        "262": "Eventide Gorge",
        "263": "Toad's Temple",
        "264": "DS DK Pass",
        "265": "Wii Koopa Cape",
        "266": "GBA Bowser Castle 2",
        "267": "GCN Dino Dino Jungle",
        "268": "Musical Cliff",
        "269": "Desert Fort",
        "270": "Camp Kartigan",
        "271": "Fort Francis",
        "272": "GCN Waluigi Stadium",
        "273": "DS Peach Gardens",
        "274": "Wii Grumble Volcano",
        "275": "SNES Bowser Castle 2",
        "276": "Forest Creek",
        "277": "Tau-Cryovolcano",
        "278": "Phendrana Frostbite",
        "279": "Siberian Chateau",
        "280": "N64 Sherbet Land",
        "281": "Wii DK Summit",
        "282": "GBA Snow Land",
        "283": "3DS DK Jungle",
        "284": "Super Marine World",
        "285": "Frantic Funyard",
        "286": "Honeybee Hideout",
        "287": "Stickerbush Serenity",
        "288": "GCN Daisy Cruiser",
        "289": "N64 Banshee Boardwalk",
        "290": "DS Waluigi Pinball",
        "291": "Wii Wario's Gold Mine",
        "292": "Coin Heaven",
        "293": "The Grand Archives",
        "294": "Midnight Museum",
        "295": "Shy Guy Lumber Co.",
        "296": "SNES Choco Island 2",
        "297": "Wii Coconut Mall",
        "298": "GBA Bowser Castle 3",
        "299": "GCN Yoshi Circuit",
        "300": "Fungal Jungle",
        "301": "Ice Cream Fortress",
        "302": "Kitayama Keep",
        "303": "Bowser Jr.'s Crafty Castle",
        "304": "DS Wario Stadium",
        "305": "Wii Toad's Factory",
        "306": "SW2 Great Question Block Ruins",
        "307": "N64 Bowser's Castle",
        "308": "BKMR Moai Mountain",
        "309": "Terra Ursae",
        "310": "Darkness Temple",
        "311": "Ghost House",
        "312": "3DS Music Park",
        "313": "Wii Moonview Highway",
        "314": "DS Airship Fortress",
        "315": "N64 Wario Stadium",
        "316": "Bluster Blob Bluff",
        "317": "Poisonous Pass",
        "318": "The Great Apple War",
        "319": "Ruinated Peach's Castle",
        "320": "N64 DK's Jungle Parkway",
        "321": "DS Delfino Square",
        "322": "Wii Maple Treeway",
        "323": "Tour Bowser Castle 3",
        "324": "Sandstone Cliffs",
        "325": "Windy Whirl",
        "326": "Quaking Mad Cliffs",
        "327": "Castle in the Sky",
        "328": "Wii Dry Dry Ruins",
        "329": "DS Tick-Tock Clock",
        "330": "GBA Bowser Castle 4",
        "331": "SNES Rainbow Road",
        "332": "Banished Keep",
        "333": "Thump Bump Forest",
        "334": "Obstagoon's Palace",
        "335": "Cruel Angel's Thesis",
        "336": "3DS Wario Shipyard",
        "337": "GBA Boo Lake",
        "338": "Wii Bowser's Castle",
        "339": "N64 Rainbow Road",
        "340": "Ghostly Gulch",
        "341": "Spooky Swamp",
        "342": "Northern Heights",
        "343": "Vile Isle",
        "344": "N64 Frappe Snowland",
        "345": "GCN Sherbet Land",
        "346": "GBA Sky Garden",
        "347": "Wii Rainbow Road",
        "348": "Cosmic Causeway",
        "349": "Aqua Dungeon",
        "350": "Garden of Dreams",
        "351": "Bowser's Termination Station",
}
